language: go

go:
  - 1.3

install:
  - sudo apt-get install protobuf-compiler
  - go get code.google.com/p/go.tools/cmd/cover
  - go get code.google.com/p/gogoprotobuf/{proto,protoc-gen-gogo,gogoproto}

script:
  - go test -v -cover
  - cd codec
  - go test -v -cover
  - cd ../transporter
  - go test -v -cover
