language: go

go:
  - 1.3

install:
  - sudo apt-get install protobuf-compiler
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/tools/godep
  - export PATH=$HOME/gopath/bin/:$PATH

script:
  - godep go test -v -cover ./...
